################################################################################
#
# Common Makefile for each test (Please include this file)
#
################################################################################

ifeq ($(origin SYSDEP_DIR), undefined)
   SYSDEP_DIR = $(TOPDIR)/sysdep
endif

ifeq ($(origin BINNAME), undefined)
   BINNAME = scale-rm
endif

ifeq ($(origin INITNAME), undefined)
   INITNAME = scale-rm_init
endif

BUILD_DIR := $(PWD)/.libs
INDEX_DIR := $(PWD)
BINDIR     = $(PWD)

include $(SYSDEP_DIR)/Makedef.$(SCALE_SYS)
include $(TOPDIR)/Mkinclude

$(BUILD_DIR)/%.f90: $(CODE_DIR)/%.f90
	mkdir -p $(BUILD_DIR)
	cp -f $< $@

build: $(patsubst %,$(BUILD_DIR)/%,$(ORG_SRCS))
	mkdir -p $(BUILD_DIR)
	$(MAKE) -C $(SCALERMDIR)/src SYSDEP_DIR=$(SYSDEP_DIR) \
                                BUILD_DIR=$(BUILD_DIR)   \
                                INDEX_DIR=$(INDEX_DIR)   \
                                BINDIR=$(BINDIR)         \
                                dynamics=$(dynamics)     \
                                sfcflx=$(sfcflx)         \
                                turbulence=$(turbulence) \
                                radiation=$(radiation)   \
                                postfix=$(postfix)

run: jobshell
	$(JOBSUB) run.sh

jobshell:
	@if [ -f ../Mkjobshell.$(SCALE_SYS).sh ]; then \
		sh ../Mkjobshell.$(SCALE_SYS).sh $(BINDIR) $(INITNAME) $(BINNAME) $(INITCONF) $(RUNCONF) $(TPROC) \
		                                 $(DATDIR) $(DATPARAM) $(DATDISTS); \
	else \
		sh $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh $(BINDIR) $(INITNAME) $(BINNAME) $(INITCONF) $(RUNCONF) $(TPROC) \
		                                            $(DATDIR) $(DATPARAM) $(DATDISTS); \
	fi



.PHONY: allclean distclean clean

allclean: distclean clean
	$(MAKE) -C $(SCALERMDIR)/src allclean BINDIR=$(BINDIR)         \
                                         BUILD_DIR=$(BUILD_DIR)   \
                                         SYSDEP_DIR=$(SYSDEP_DIR)

distclean: clean
	$(MAKE) -C $(SCALERMDIR)/src distclean BINDIR=$(BINDIR)         \
                                          BUILD_DIR=$(BUILD_DIR)   \
                                          SYSDEP_DIR=$(SYSDEP_DIR)
	rm -f *.nc *LOG.pe* monitor.pe* latlon* run.sh

clean:
	$(MAKE) -C $(SCALERMDIR)/src clean BINDIR=$(BINDIR)         \
                                      BUILD_DIR=$(BUILD_DIR)   \
                                      SYSDEP_DIR=$(SYSDEP_DIR)

