################################################################################
#
# Makefile for each test program
#
################################################################################

PWD         = $(shell pwd)
TOPDIR      = $(abspath ../../../../..)
TESTDIR     = ../../..


# user-defined source files
CODE_DIR    = .
ORG_SRCS    =


# parameters for run
PPNAME      = scale-les_pp
INITNAME    = scale-les_init
BINNAME     = scale-les
PPCONF      = pp.conf
INITCONF    = init.conf
RUNCONF     = run.conf
TPROC       = 9


# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
