################################################################################
#
# Makefile for each test project
# %> make clean       (cleanup)
# %> make depends     (generate depends.info and include)
# %> make
#
# if you have the problem about compilation order,
# please try the following commands;
#
# %> make -n       (display all procedure for check)
# or
# %> make -B       (ignore the timestamp)
#
################################################################################

TOPDIR = ../../..

include $(TOPDIR)/sysdep/Makedef.$(SCALE_SYS)
include $(TOPDIR)/src/Mkinclude

VPATH = ../../common:../../io:../../grid:../../atmos:../../ocean:../../preprocess
INDEX_DIR = $(INCDIR)

#default index & tracer set
index     = 206x24x24
tracer    = kessler
precision = real8
sfcflx    = louis
radiation = mstrnX
postfix   = 

PROJ_EXE = #PROJECT#

all: makedir makedcutils makegtool makeinclude makebin

makedcutils:
	cd $(DCUTILSDIR); $(MAKE)

makegtool:
	cd $(GTOOLDIR); $(MAKE)

makedir:
	mkdir -p $(BINDIR)
	mkdir -p $(LIBDIR)

makeinclude:
	cp $(INDEX_DIR)/inc_index_$(index).f90      inc_index.h
	cp $(INCDIR)/inc_tracer_$(tracer).f90       inc_tracer.h
	cp $(INCDIR)/inc_precision_$(precision).f90 inc_precision.h

makebin: $(PROJ_EXE)
	install $(PROJ_EXE) $(BINDIR)/$(PROJ_EXE)_$(SUFFIX)

$(PROJ_EXE): $(PROJ_EXE).o $(LIBNAME) $(LIBDIR)/libgtool.a $(LIBDIR)/libdcutils.a
	$(FC) $(LFLAGS) -o $@ $^ $(NETCDF_LIBS)

$(LIBNAME): $(MODS)
	$(AR) $(ARFLAGS) $@ $(MODS)
	$(RANLIB) $@


.SUFFIXES:
.SUFFIXES: .o .f90 .f .c

%.o : %.f90
	$(FC) $(FFLAGS) -I./ -I$(GTOOLDIR) -I$(DCUTILSDIR) -I$(DCUTILSDIR) -I$(INCDIR) -o $@ -c $<

.c.o:
	$(CC)  $(CFLAGS) -o $@ -c $<

%.o: %.mod

.PHONY: depends freeze copylocal mktar clean distclean allclean

clean:
	rm -f *.mod *.o *.lst depends.info

distclean: clean
	rm -f $(PROJ_EXE) *.a *.h *~

allclean: distclean
	$(MAKE) -C $(DCUTILSDIR) allclean
	$(MAKE) -C $(GTOOLDIR)   allclean

freeze: clean depends copylocal mktar

copylocal:
	@for i in $(MODSRC) ; do \
		cp $$i . ; \
	done
	cp ../../sysdep/Makedef.$(SCALE_SYS) .

mktar:
	tar -czf ../$(PROJ_EXE).tgz ./

depends:
	@../mkdepends.pl $(PROJ_EXE) $(VPATH)

-include depends.info
