################################################################################
#
# Common Makefile for each test (Please include this file)
#
################################################################################

include $(TOPDIR)/Mkinclude
include $(SYSDEP_DIR)/Makedef.$(SCALE_SYS)

BUILD_DIR := $(PWD)/.libs
INDEX_DIR := $(PWD)

BINDIR     = $(PWD)
SRCDIR     = $(SCALELESDIR)/src

ifeq ($(origin BINNAME), undefined)
   BINNAME = scale-les
endif

ifeq ($(origin INITNAME), undefined)
   INITNAME = scale-les_init
endif

$(BUILD_DIR)/%.f90: $(CODE_DIR)/%.f90
	cp -f $< $@

build: makedir $(patsubst %,$(BUILD_DIR)/%,$(ORG_SRCS))
	$(MAKE) -C $(SRCDIR) BINDIR=$(BINDIR)         \
                        BUILD_DIR=$(BUILD_DIR)   \
                        SYSDEP_DIR=$(SYSDEP_DIR) \
                        index=$(index)           \
                        precision=$(precision)   \
                        tracer=$(tracer)         \
                        dynamics=$(dynamics)     \
                        sfcflx=$(sfcflx)         \
                        turbulence=$(turbulence) \
                        radiation=$(radiation)   \
                        postfix=$(postfix)

dcutils:
	$(MAKE) -C $(SRCDIR) dcutils SYSDEP_DIR=$(SYSDEP_DIR)

gtool:
	$(MAKE) -C $(SRCDIR) gtool   SYSDEP_DIR=$(SYSDEP_DIR)

scalelib:
	$(MAKE) -C $(SRCDIR) scalelib                 \
                        BINDIR=$(BINDIR)         \
                        BUILD_DIR=$(BUILD_DIR)   \
                        SYSDEP_DIR=$(SYSDEP_DIR) \
                        index=$(index)           \
                        precision=$(precision)   \
                        tracer=$(tracer)         \
                        dynamics=$(dynamics)     \
                        sfcflx=$(sfcflx)         \
                        turbulence=$(turbulence) \
                        radiation=$(radiation)   \
                        postfix=$(postfix)

makedir:
	mkdir -p $(BUILD_DIR)

run: jobshell
	$(JOBSUB) run.sh

jobshell:
	@if [ -f ../Mkjobshell.$(SCALE_SYS).sh ]; then \
		sh ../Mkjobshell.$(SCALE_SYS).sh $(BINDIR) $(INITNAME) $(BINNAME) $(INITCONF) $(RUNCONF) $(TPROC); \
	else \
		sh $(SYSDEP_DIR)/Mkjobshell.$(SCALE_SYS).sh $(BINDIR) $(INITNAME) $(BINNAME) $(INITCONF) $(RUNCONF) $(TPROC); \
	fi



.PHONY: allclean distclean clean

allclean: distclean clean
	$(MAKE) -C $(SRCDIR) allclean BINDIR=$(BINDIR)         \
                                 BUILD_DIR=$(BUILD_DIR)   \
                                 SYSDEP_DIR=$(SYSDEP_DIR)

distclean: clean
	$(MAKE) -C $(SRCDIR) distclean BINDIR=$(BINDIR)         \
                                  BUILD_DIR=$(BUILD_DIR)   \
                                  SYSDEP_DIR=$(SYSDEP_DIR)
	rm -f *.nc *LOG.pe* monitor.pe* latlon* run.sh

clean:
	$(MAKE) -C $(SRCDIR) clean BINDIR=$(BINDIR)         \
                              BUILD_DIR=$(BUILD_DIR)   \
                              SYSDEP_DIR=$(SYSDEP_DIR)

