################################################################################
#
# Makefile for each test program
#
################################################################################

PWD         = $(shell pwd)
TOPDIR      = $(abspath ../../../../..)
TESTDIR     = ../../..


# user-defined source files
CODE_DIR    = .
ORG_SRCS    =

# parameters for run
INITCONF    = 
RUNCONF     = 
TPROC       = 

# required data (parameters,distributed files)
DATDIR      = 
DATPARAM    = 
DATDISTS    =

# options
export AGGRESSIVE = T


# build, makedir, run, jobshell, allclean, clean is inside of common Makefile
include $(TESTDIR)/Makefile.common
