################################################################################
#
# Makefile for each job
#
################################################################################

all: 
	make clean
	sh config/mkconf.sh

.PHONY: clean

clean:
	rm -f base.*.conf param.*.conf
	rm -rf output
